[general]
email = ""

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#c9a84c"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#14192e"
font = "serif"
