[general]
email = ""

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#c9a84c"
backgroundColor = "#f5e6b8"
secondaryBackgroundColor = "#ede0a8"
textColor = "#14192e"
font = "serif"
